version: "3.9"
networks:
  localdev:
    name: "localdev"

services:
  web:
    build: .
    restart: "always"
    ports:
      - "7000:80"
    depends_on:
      - db
    networks:
      - localdev
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    networks:
      - localdev

